// <auto-generated />
namespace OnlineFoodOrdering.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updatepro31 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatepro31));
        
        string IMigrationMetadata.Id
        {
            get { return "201708271324345_updatepro31"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
